#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Com.Wikitude.Samples.Resource", IsApplication=true)]

namespace Com.Wikitude.Samples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int architectView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int buttonLaunchUrl = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int button_visit_url = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int poi_description = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int poi_latitude = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int poi_longitude = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int poi_title = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int url = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int list_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int list_sample = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_startscreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int sample_1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int sample_5_1_poidetail = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sample_cam = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int urllauncher_main = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int compass_accuracy_low = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int device_unsupported = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int hello_world = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int location_fetching = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int main_title_urlLauncher = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int menu_settings = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int poi_description = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int poi_latitude = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int poi_longitude = 2130968590;
			
			// aapt resource value: 0x7f04000b
			public const int poi_name = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int title_activity_sample1_poi_detail = 2130968591;
			
			// aapt resource value: 0x7f040006
			public const int urllauncher_button_launch = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int urllauncher_default_value_textfield = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int urllauncher_hint_textfield = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int urllauncher_menu_clear_history = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AutoCompleteTextViewLight = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int Widget_DropDownItemLight = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
